services:
  db:
    image: postgres:17
    container_name: pg-course-db
    environment:
      POSTGRES_DB: Deanery
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
      TZ: Europe/Moscow
    ports:
      - "55432:5432"
    volumes:
      - pg_course_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d Deanery"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  flyway:
    image: flyway/flyway:10
    profiles:
      - tools
    depends_on:
      db:
        condition: service_healthy
    command: -connectRetries=60 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/Deanery
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: admin_pass
      FLYWAY_DEFAULT_SCHEMA: public
    volumes:
      - ./s2/db/migrations:/flyway/sql:ro

volumes:
  pg_course_data:
